<?php
//préfixe
    $rep=__DIR__.'/../';
//BD
    $dsn='mysql:host=localhost;dbname=projet';
    $login="root";
    $mdp="1234";
//Vues
    $vues['erreur']="Vues/Erreur.php";
    $vues['admin']="Vues/admin.php";
    $vues['user']="Vues/user.php";
?>